{{- if or .Values.encode.create .Values.prefillDecode.create }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vllm-shared-storage
  namespace: {{default .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: local-fs
  resources:
    requests:
      storage: 50Gi
{{- end }}

# Made with Bob
